import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber/Navber";
import Footer from "./components/Footer/Footer";


const ibmPlex = IBM_Plex_Sans({
  variable: "--font-ibm-plex",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      dir="rtl"
      className={`${ibmPlex.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Navber/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}